name: widger-server pipe DockerHub

on:
    push: 
        branches:
            - main

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - name: Generate tag
              id: tag
              run: |
                SHA=$(echo $GITHUB_SHA | head -c7)
                echo "sha=$SHA" >> $GITHUB_OUTPUT

                
        #     - name: Checkout
        #       id: checkout
        #       uses: actions/checkout@v4 

        #     - name: Generate tag
        #       id: tag
        #       run: |
        #         SHA=$(echo $GITHUB_SHA | head -c7)
        #         echo "sha=$SHA" >> $GITHUB_OUTPUT

        #     - name: Login to Docker Hub
        #       uses: docker/login-action@v3
        #       with:
        #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
        #         password: ${{ secrets.DOCKER_HUB_TOKEN }}


        #     - name: Build and push the image to AWS ECR
        #       id: build-and-push
        #       env:
        #         DOCKER_HUB_REPOSITORY: ${{ vars.DOCKER_HUB_REPOSITORY }}
        #         IMAGE_TAG: ${{ steps.tag.outputs.sha }}
        #       run: |
        #         docker build -t $DOCKER_HUB_REGISTRY:$IMAGE_TAG .
        #         docker push $DOCKER_HUB_REGISTRY:$IMAGE_TAG
            